# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Michael Hassid
email: michael.hassid@mail.huji.ac.il
description: >- # this means to ignore newlines until "baseurl:"
  Homepage of Michael Hassid, PhD candidate at the Hebrew University and research assistant at FAIR (Meta).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MichaelHassid
github_username:  hassidm

# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gefile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


defaults:
   - scope:
        path: ""
     values:
#        author_profile: true

# Site owner
author:
  name: "Michael Hassid"
  avatar: "/assets/images/bio-photo.jpg"              
  bio: "PhD candidate at HUJI;<br> Research Assistant at FAIR (Meta)"
  links:
        - label: ""
          icon: "far fa-paper-plane"
          url: "mailto:michael.hassid@mail.huji.ac.il"
        - label: ""
          icon: "fab fa-twitter"
          url: "https://x.com/MichaelHassid"
        # - label: ""
        #   icon: "fab fa-fw fa-github"
        #   url: "https://github.com/gabrielStanovsky"
        - label: ""
          icon: "fas fa-university"
          url: "https://scholar.google.com/citations?hl=en&user=5d93np0AAAAJ"
        - label: ""
          icon: "fab fa-fw fa-linkedin-in"
          url: "https://www.linkedin.com/in/michael-hassid-8475271ab/"

        


          
